CREATE DATABASE MENAIER_DB
GO
USE MENAIER_DB
GO
CREATE TABLE MARCAS
(
	IDMARCA INT NOT NULL IDENTITY(40000000,1) PRIMARY KEY,
	DESCRIPCION VARCHAR(60) NOT NULL
)
GO
CREATE TABLE TIPOSPRODUCTO
(
	IDTIPO INT NOT NULL IDENTITY(50000000,1) PRIMARY KEY,
	DESCRIPCION VARCHAR(60) NOT NULL
)
GO
CREATE TABLE CLIENTES
(
	IDCLIENTE INT NOT NULL PRIMARY KEY,
	CUIT INT,
	EMPRESA VARCHAR(60),
	TIPOCLIENTE CHAR(2) NOT NULL,
)
GO
CREATE TABLE CONTACTOS
(
	IDCONTACTO INT NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(60) NOT NULL,
	APELLIDO VARCHAR(60) NOT NULL,
	DNI INT,
	EMAIL VARCHAR(60) NOT NULL
)
GO
CREATE TABLE PROVEEDORES
(
	IDPROVEEDOR INT NOT NULL PRIMARY KEY,
	EMPRESA VARCHAR(60) NOT NULL,
	CUIT INT NOT NULL
)
GO
CREATE TABLE EMPLEADOS
(
	NOMBRE VARCHAR(60) NOT NULL,
	APELLIDO VARCHAR(60) NOT NULL,
	DNI INT NOT NULL,
 	IDEMPLEADO INT NOT NULL IDENTITY(10000000,1) PRIMARY KEY,
	FECHANAC DATE,
	USUARIO VARCHAR(60) NOT NULL,
	CONTRASENIA VARCHAR(60) NOT NULL,
	TIPOPERFIL CHAR(2) NOT NULL,
	EMAIL VARCHAR(60) NOT NULL
)
GO
CREATE TABLE PRODUCTOS
(
	IDPRODUCTO INT NOT NULL PRIMARY KEY,
	IDMARCA INT NOT NULL FOREIGN KEY REFERENCES MARCAS(IDMARCA),
	IDTIPO INT NOT NULL FOREIGN KEY REFERENCES TIPOSPRODUCTO(IDTIPO),
	DESCRIPCION VARCHAR(60) NOT NULL,
	PRECIO MONEY NOT NULL,
	STOCKMIN INT NOT NULL,
	GANANCIA FLOAT NOT NULL
)
GO
CREATE TABLE LOTES
(
	IDLOTE INT NOT NULL PRIMARY KEY,
	IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(IDPRODUCTO),
	CANTIDAD INT NOT NULL,
	COSTOPU FLOAT NOT NULL,
	FECHACOMPRA DATE NOT NULL,
	FECHAVENCIMIENTO DATE
)
GO
CREATE TABLE VENTAS
(
	IDVENTA INT NOT NULL PRIMARY KEY,
	FECHA DATE NOT NULL,
	IDEMPLEADO INT NOT NULL FOREIGN KEY REFERENCES EMPLEADOS(IDEMPLEADO),
	IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE)
)
GO
CREATE TABLE COMPRAS
(
	IDCOMPRA INT NOT NULL PRIMARY KEY,
	FECHA DATE NOT NULL,
	IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(IDPROVEEDOR)
)
GO
CREATE TABLE LOTES_X_VENTA
(
	IDVENTA INT NOT NULL FOREIGN KEY REFERENCES VENTAS(IDVENTA),
	IDLOTE INT NOT NULL FOREIGN KEY REFERENCES LOTES(IDLOTE),
	PRIMARY KEY (IDVENTA, IDLOTE)
)
GO
CREATE TABLE LOTES_X_COMPRA
(
	IDCOMPRA INT NOT NULL FOREIGN KEY REFERENCES COMPRAS(IDCOMPRA),
	IDLOTE INT NOT NULL FOREIGN KEY REFERENCES LOTES(IDLOTE),
	PRIMARY KEY (IDCOMPRA, IDLOTE)
)
GO
CREATE TABLE CONTACTOS_X_CLIENTE
(
	IDCONTACTO INT NOT NULL FOREIGN KEY REFERENCES CONTACTOS(IDCONTACTO),
	IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE),
	PRIMARY KEY (IDCONTACTO, IDCLIENTE)
)
GO
CREATE TABLE CONTACTOS_X_PROVEEDOR
(
	IDCONTACTO INT NOT NULL FOREIGN KEY REFERENCES CONTACTOS(IDCONTACTO),
	IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(IDPROVEEDOR),
	PRIMARY KEY (IDCONTACTO, IDPROVEEDOR)
)
GO
CREATE TABLE PRODUCTOS_X_PROVEEDOR
(
	IDPROVEEDOR INT NOT NULL FOREIGN KEY REFERENCES PROVEEDORES(IDPROVEEDOR),
	IDPRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(IDPRODUCTO),
	PRIMARY KEY (IDPROVEEDOR, IDPRODUCTO)
)
GO
CREATE TABLE TELEFONOS_X_EMPLEADO
(
	IDEMPLEADO INT NOT NULL FOREIGN KEY REFERENCES EMPLEADOS(IDEMPLEADO),
	NUMERO INT NOT NULL,
	DESCRIPCION VARCHAR(60) NOT NULL
)
GO
CREATE TABLE DOMICILIOS_X_EMPLEADO
(
	IDEMPLEADO INT NOT NULL FOREIGN KEY REFERENCES EMPLEADOS(IDEMPLEADO),
	CALLE VARCHAR(60) NOT NULL,
	ALTURA INT NOT NULL,
	PISO VARCHAR(10),
	BARRIO VARCHAR(60) NOT NULL,
	CIUDAD VARCHAR(60) NOT NULL,
	PAIS VARCHAR(60)
)
CREATE TABLE TELEFONOS_X_CONTACTO
(
	IDCONTACTO INT NOT NULL FOREIGN KEY REFERENCES CONTACTOS(IDCONTACTO),
	NUMERO INT NOT NULL,
	DESCRIPCION VARCHAR(60) NOT NULL
)
GO
CREATE TABLE DOMICILIOS_X_CONTACTO
(
	IDCONTACTO INT NOT NULL FOREIGN KEY REFERENCES CONTACTOS(IDCONTACTO),
	CALLE VARCHAR(60) NOT NULL,
	ALTURA INT NOT NULL,
	PISO VARCHAR(10),
	BARRIO VARCHAR(60) NOT NULL,
	CIUDAD VARCHAR(60) NOT NULL,
	PAIS VARCHAR(60)
)
CREATE TABLE TELEFONOS_X_CLIENTE
(
	IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE),
	NUMERO INT NOT NULL,
	DESCRIPCION VARCHAR(60) NOT NULL
)
GO
CREATE TABLE DOMICILIOS_X_CLIENTE
(
	IDCLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE),
	CALLE VARCHAR(60) NOT NULL,
	ALTURA INT NOT NULL,
	PISO VARCHAR(10),
	BARRIO VARCHAR(60) NOT NULL,
	CIUDAD VARCHAR(60) NOT NULL,
	PAIS VARCHAR(60)
)
GO

SET DATEFORMAT dmy;

INSERT INTO EMPLEADOS([Nombre],[Apellido],[DNI],[FECHANAC],[USUARIO],[CONTRASENIA],[TIPOPERFIL],[EMAIL]) VALUES ('Amery','Moss',28865175,'09/11/1978','AMoss','Paesj7541','A','amoss@gmail.com'),('Colleen','Wright',15631367,'25/12/1978','CWright','Obecm7263','S','cwright@gmail.com');
INSERT INTO EMPLEADOS([Nombre],[Apellido],[DNI],[FECHANAC],[USUARIO],[CONTRASENIA],[TIPOPERFIL],[EMAIL]) VALUES ('Maggie','Pacheco',18975273,'10/01/1980','MPachecho','Zyycm8013','S','mpacheco@gmail.com'),('Ray','Humphrey',15473566,'07/06/1981','RHumphrey','Xmgkv9023','V','rhumphrey@gmail.com');
INSERT INTO EMPLEADOS([Nombre],[Apellido],[DNI],[FECHANAC],[USUARIO],[CONTRASENIA],[TIPOPERFIL],[EMAIL]) VALUES ('Hiram','Brown',33547894,'02/08/1996','HBrown','Gmsvu3029','V','hbrown@gmail.com'),('Jaime','Keller',29945252,'26/03/1995','JKeller','Cssvj1840','V','jkeller@gmail.com');
INSERT INTO EMPLEADOS([Nombre],[Apellido],[DNI],[FECHANAC],[USUARIO],[CONTRASENIA],[TIPOPERFIL],[EMAIL]) VALUES ('Raymond','Lindsey',15167996,'17/09/1988','RLindsey','Vwogm3069','V','rlindsey@gmail.com'),('Maryam','Watson',25354035,'11/11/1989','MWatson','Gdjbz6456','V','mwatson@gmail.com');

INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Un Rincon Vegano');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Las Vacas Felices');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Vegetalex');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Lucchetti');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Delicias Doradas');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Doritos');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Lays');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Arrocitas');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Mister Veggie');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Matarazzo');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Coca Cola');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Pepsi');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('McCain');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Mi Soja');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Pureza');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Chango');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Natura');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Dánica');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Dame Mani');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Águila');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Soyana');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Virgen');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Titan');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Cachafaz');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Granix');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Oreo');
INSERT INTO MARCAS([DESCRIPCION]) VALUES ('Successo');

INSERT INTO TIPOSPRODUCTO([DESCRIPCION]) VALUES ('Golosinas');
INSERT INTO TIPOSPRODUCTO([DESCRIPCION]) VALUES ('Congelados');
INSERT INTO TIPOSPRODUCTO([DESCRIPCION]) VALUES ('Refrigerados');
INSERT INTO TIPOSPRODUCTO([DESCRIPCION]) VALUES ('Snacks');
INSERT INTO TIPOSPRODUCTO([DESCRIPCION]) VALUES ('Bebidas');
INSERT INTO TIPOSPRODUCTO([DESCRIPCION]) VALUES ('Galletitas');
INSERT INTO TIPOSPRODUCTO([DESCRIPCION]) VALUES ('Enlatados');
INSERT INTO TIPOSPRODUCTO([DESCRIPCION]) VALUES ('No perecederos');